#!/bin/sh
./local/kind/kind-setup
./knative/serving
./knative/networking/kourier
./knative/eventing
./knative/brokers/in-memory
./knative/observability
echo "Ignore Istio warnings 🔧"
echo "Installation finished 🎈🎈🎈"
