#!/bin/sh -e
NETWORKING=${NETWORKING:-kourier}
BROKER=${BROKER:-kafka}

kind delete cluster --name=local-cluster || echo "no local-cluster to delete 🤷🏻"
./local/pre-validate
./local/kind/kind-setup
NETWORKING=${NETWORKING} BROKER=${BROKER} ./local/knative
echo "Installation finished 🎈🎈🎈"
