#!/bin/sh -e
istioctl operator init
kubectl apply -f ./knative/networking/istio-minimal-operator.yaml
count=0
until [ $count -ge 4 ]
do
    sleep 5
    count=`kubectl get deploy -n istio-system | wc -l`
done
kubectl wait --timeout=120s -n istio-system --for condition=Available deploy istio-ingressgateway cluster-local-gateway
kubectl apply --filename https://github.com/knative/net-istio/releases/download/v0.18.0/release.yaml
kubectl --namespace istio-system get service istio-ingressgateway
