#!/bin/sh -e
kubectl apply -f https://github.com/knative/net-kourier/releases/download/v0.18.0/kourier.yaml
echo "⏳ waiting for kourier ingress system to become healthy"
kubectl wait --timeout=120s deployment 3scale-kourier-gateway --for=condition=Available -n kourier-system
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: kourier-ingress
  namespace: kourier-system
  labels:
    networking.knative.dev/ingress-provider: kourier
spec:
  type: NodePort
  selector:
    app: 3scale-kourier-gateway
  ports:
    - name: http2
      nodePort: 31080
      port: 80
      targetPort: 8080
EOF
kubectl patch configmap/config-network \
  --namespace knative-serving \
  --type merge \
  --patch '{"data":{"ingress.class":"kourier.ingress.networking.knative.dev"}}'
kubectl get pods -n kourier-system
kubectl get svc  -n kourier-system kourier-ingress

