#!/bin/sh -e
k3d cluster create local-cluster  -p 443:31445@loadbalancer -p 80:31080@loadbalancer --k3s-server-arg --no-deploy --k3s-server-arg traefik
# kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
