#!/bin/sh
kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.17.0/eventing-crds.yaml
kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.17.0/eventing-core.yaml
kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.17.0/in-memory-channel.yaml
kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.17.0/mt-channel-broker.yaml
kubectl get pods --namespace knative-eventing
kubectl wait deployment eventing-webhook --for=condition=Available -n knative-eventing

