#!/bin/sh -e
kubectl apply -f https://github.com/knative/serving/releases/download/v0.18.0/serving-crds.yaml
kubectl apply -f https://github.com/knative/serving/releases/download/v0.18.0/serving-core.yaml
./knative/feature-toogles
echo "⏳ waiting for knative-serving to become healthy"
kubectl wait --timeout=120s deployment activator autoscaler controller webhook --for=condition=Available -n knative-serving
kubectl get pods -n knative-serving
