apiVersion: v1
kind: Service
metadata:
  name: broker-ingress
  namespace: knative-eventing
spec:
  selector:
    app: kafka-broker-receiver
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080

